#!/usr/bin/env bash
#
# Configures nginx to redirect /redirect_me to another page with a 301

apt-get update
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

sed -i '/listen 80 default_server;/a\
        location /redirect_me {\
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
        }' /etc/nginx/sites-available/default

service nginx restart